<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CampaignAttribution extends Model
{
    protected $fillable = [
        'lead_id',
        'interest_id',
        'opportunity_id',
        'platform',
        'account_id',
        'campaign_id',
        'campaign_name',
        'campaign_name_key',
        'source_acquired',
        'medium_acquired',
        'campaign_acquired',
        'acquired_id',
        'acquired_id_key',
        'content_acquired',
        'content_acquired_key',
        'vehicle_interest',
        'lead_status',
        'lead_created_at',
        'interest_functional_created_at',
        'interest_status',
        'interest_type',
        'interest_source',
        'interest_original_source',
        'interest_medium',
        'interest_channel',
        'interest_utm_term',
        'interest_origin_delegation',
        'interest_origin_zone',
        'interest_owner_id',
        'interest_owner_name',
        'interest_is_deleted',
        'interest_sync_run_id',
        'interest_sync_cutoff_at',
        'opportunity_relationship_status',
        'opportunity_created_at',
        'reservation_date',
        'sale_date',
        'sale_amount',
        'has_opportunity',
        'has_reservation',
        'has_fallen_reservation',
        'has_sale',
        'lead_delegation',
        'lead_zone',
        'commercial_user_id',
        'commercial_user_name',
        'attribution_method',
        'attribution_confidence',
        'opportunity_attribution_method',
        'opportunity_attribution_confidence',
        'match_status',
        'campaign_source_type',
        'matched_source_field',
        'matched_source_value',
        'matched_platform_field',
        'matched_platform_value',
        'match_candidate_count',
    ];

    protected $casts = [
        'lead_created_at' => 'datetime',
        'interest_functional_created_at' => 'datetime',
        'interest_sync_cutoff_at' => 'datetime',
        'interest_is_deleted' => 'boolean',
        'opportunity_created_at' => 'datetime',
        'reservation_date' => 'date',
        'sale_date' => 'date',
        'sale_amount' => 'decimal:2',
        'has_opportunity' => 'boolean',
        'has_reservation' => 'boolean',
        'has_fallen_reservation' => 'boolean',
        'has_sale' => 'boolean',
    ];
}
